spring.application.name=currency-conv
server.port=8000
#spring.config.import=optional:configserver:http://localhost:8888

spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
#http://localhost:8000/currency-conversion/USD/to/INR/quantity/100020

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#docker run -p 9411:9411 openzipkin/zipkin
feign.micrometer.enabled=true
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
logging.pattern.level=%d{HH:mm:ss} %5p [${spring.application.name},%X{traceId:-},%X{spanId:-}] %logger - %msg%n
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

#kafka properties
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3



